### PR TITLE
fix bugs when using py 3.6

### PR DESCRIPTION
**Pull request by dongchirua**
1. fixed places where `print` functions are invoked
2. fixed include headers

### CODE REVIEW

**Comment by dongchirua** [comment]
@josepablog I have changed as you requested :)

**Comment by josepablog** [comment]
Very sorry for the back and forth, but I think if we follow semantic versioning (https://semver.org) it should be 0.9.0, this is not a bug fix, and we are breaking compatibility.

**Comment by josepablog** [comment]
thank you for the work

**Comment by dongchirua** [comment]
@josepablog I changed :) please check

**Comment by josepablog** [comment]
thank you for your help with this!

**Pull request merged**
